title: 'Untitled-1'
# choose from Breeze, Candy, Crimson, Falcon, Meadow, Midnight, Raindrop, Sunset
theme: Breeze
# choose from 16, 32, 64, 128
padding: 32
background: true
dark-mode: true
language: auto
spoiler: false
print-url: false

channels:
  - id: '1234567890987654321'
    theme: Midnight
    padding: 64
    spoiler: true
    print-url: true
