default:
  title: 'Untitled-1'
  # choose from breeze, candy, crimson, falcon, meadow, midnight, raindrop, sunset
  theme: breeze
  # choose from 16, 32, 64, 128
  padding: 32
  background: true
  dark-mode: true
  language: auto
  spoiler: false
  generate-url: false

guilds: # optional
  - id: '123456789123456789' # discord server id
    theme: candy
    padding: 64
    dark-mode: false
    generate-url: true
    channels:
      - id: '1234567890987654321' # discord channel id
        theme: midnight
        spoiler: true
        generate-url: false
